# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - umi_planner_controller

  umi_planner_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - UMIRobot_joint_1
      - UMIRobot_joint_2
      - UMIRobot_joint_3
      - UMIRobot_joint_4
  